# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/mainPUKwxW.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_key_tab1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_key_tab1.setObjectName("lineEdit_key_tab1")
        self.verticalLayout_2.addWidget(self.lineEdit_key_tab1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.plainTextEdit_data_tab1 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_data_tab1.setObjectName("plainTextEdit_data_tab1")
        self.verticalLayout_2.addWidget(self.plainTextEdit_data_tab1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_cover_tab1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_cover_tab1.setObjectName("lineEdit_cover_tab1")
        self.horizontalLayout_2.addWidget(self.lineEdit_cover_tab1)
        self.browse_btn = QtWidgets.QPushButton(self.tab)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_2.addWidget(self.browse_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.encode_btn = QtWidgets.QPushButton(self.tab)
        self.encode_btn.setObjectName("encode_btn")
        self.verticalLayout_2.addWidget(self.encode_btn)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_cover_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_cover_tab2.setObjectName("lineEdit_cover_tab2")
        self.horizontalLayout.addWidget(self.lineEdit_cover_tab2)
        self.browse_btn2 = QtWidgets.QPushButton(self.tab_2)
        self.browse_btn2.setObjectName("browse_btn2")
        self.horizontalLayout.addWidget(self.browse_btn2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_stego_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_stego_tab2.setObjectName("lineEdit_stego_tab2")
        self.horizontalLayout_3.addWidget(self.lineEdit_stego_tab2)
        self.browse_btn3 = QtWidgets.QPushButton(self.tab_2)
        self.browse_btn3.setObjectName("browse_btn3")
        self.horizontalLayout_3.addWidget(self.browse_btn3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.recoverqr_btn = QtWidgets.QPushButton(self.tab_2)
        self.recoverqr_btn.setObjectName("recoverqr_btn")
        self.verticalLayout_3.addWidget(self.recoverqr_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lineEdit_key_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_key_tab2.setObjectName("lineEdit_key_tab2")
        self.verticalLayout_3.addWidget(self.lineEdit_key_tab2)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.plainTextEdit_enc_tab2 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_enc_tab2.setObjectName("plainTextEdit_enc_tab2")
        self.verticalLayout_3.addWidget(self.plainTextEdit_enc_tab2)
        self.decrypt_btn = QtWidgets.QPushButton(self.tab_2)
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.verticalLayout_3.addWidget(self.decrypt_btn)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QRSteg"))
        self.label.setText(_translate("MainWindow", "Key"))
        self.label_2.setText(_translate("MainWindow", "Data"))
        self.label_3.setText(_translate("MainWindow", "Select Cover Image"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.encode_btn.setText(_translate("MainWindow", "Encode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Encode"))
        self.label_4.setText(_translate("MainWindow", "Select Cover Image"))
        self.browse_btn2.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Select Stego Image"))
        self.browse_btn3.setText(_translate("MainWindow", "Browse"))
        self.recoverqr_btn.setText(_translate("MainWindow", "Recover QR"))
        self.label_6.setText(_translate("MainWindow", "Key"))
        self.label_7.setText(_translate("MainWindow", "Encypted Message"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Decode"))

